apiVersion: v1
kind: Service
metadata:
  name: deploydemo-2
  namespace: kube-public
  labels:
    app.kubernetes.io/name: deploydemo-2
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: deploydemo-2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000